## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [1]:
import numpy as np
import pandas as pd
import scipy as stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [7]:
samples = np.random.normal(100, 15, 1000 )
# random.normal(loc=0.0, scale=1.0, size=None)
# loc:float or array_like of floats
# Mean (“centre”) of the distribution.
# scale:float or array_like of floats
# Standard deviation (spread or “width”) of the distribution. Must be non-negative.
# size:int or tuple of ints, optional
# Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. If size is None (default), a single value is returned if loc and scale are both scalars. Otherwise, np.broadcast(loc, scale).size samples are drawn.

In [6]:
samples

array([ 97.21434455,  99.99721673,  93.36021263,  99.21958022,
       112.41679103,  80.31050295,  97.07465561, 112.90360349,
        78.51992549, 111.52491726, 104.70340324, 115.30214803,
        93.36831067,  93.36353011, 102.70520135, 110.88489553,
        93.34216753, 106.81654649, 101.7659317 ,  92.17841895,
       131.39259761, 127.57562024,  80.29667304, 104.96686265,
       100.08953698, 110.39353078,  71.81721233,  93.92540013,
       101.93673299,  79.07027516, 129.97118155,  89.62768494,
        99.16909446,  96.44294554, 103.74210402, 104.12375192,
       105.95668522,  99.92006789,  87.06070343, 110.79019052,
        91.37525245, 116.04535485, 105.15671069,  86.64392888,
        62.44473474,  93.79522828, 116.90974738, 117.05068258,
        98.00937246, 100.10180599,  87.83123518, 104.01093183,
        90.90451382,  91.47790101, 103.25048919,  82.60521258,
        81.63107063,  94.42055767,  88.91414503, 104.07282053,
        89.68757916,  90.24690536,  96.70085526,  59.19637585,
       110.54656166, 122.23617241,  76.98330295, 117.40417906,
        81.66495444, 112.91632735, 100.85726307,  97.30813903,
        94.95460963, 128.2864674 ,  68.36598882,  76.32082199,
       110.27904761, 105.53723229,  80.85765573, 108.61382929,
       123.62601467, 106.65490135,  96.58417022, 118.55286205,
        78.80699362, 108.78294391,  82.36538125, 116.91825836,
        95.8799641 ,  88.13232302, 109.58418339,  92.16638689,
       102.31017751, 103.59647943, 114.3952961 ,  97.87893642,
       109.69801693, 129.74312808, 115.16886268, 134.07779897,
       105.8388451 ,  82.75459102, 105.0623358 ,  97.71053191,
        79.92335841, 115.0919396 ,  84.98324607, 100.44306674,
       102.32704249,  93.61567736, 125.31592002, 102.94224996,
       130.49835214,  81.38908421, 102.7825863 , 113.79883831,
       110.56404773, 101.4117552 ,  74.29474201,  92.18472554,
        92.60719435,  91.3521637 , 117.6621242 ,  87.98854089,
       119.49364785, 106.6114667 ,  74.94921315,  99.6696757 ,
        92.88259037, 120.91782196, 111.6247742 ,  95.4076165 ,
       128.98344399, 101.63464147,  90.5380427 , 104.18912412,
       110.69633433, 114.6928667 ,  74.88204844,  99.37559085,
       101.51279559, 101.80499792, 112.63753776, 102.68658232,
       121.11013999,  98.85977254, 104.37752596, 128.07335629,
       127.11330657, 135.58146597,  88.95318371, 112.29227592,
        89.61509137,  88.88252053,  98.90519356, 109.37490762,
       114.04784317,  78.30148885, 125.61725886,  89.46790037,
        99.58202382, 115.97392995,  96.66607635, 101.85443514,
        86.13827561,  90.24051546, 100.45957832,  96.93615844,
       102.85362453,  86.02322716,  95.02246523,  94.10334663,
        85.63076979,  85.70930603, 104.015406  , 114.84321183,
       109.92503108, 103.88551059, 113.70402436, 100.46629772,
        81.57195828,  85.07578605,  86.67121417,  74.21242332,
        76.26505265, 102.89994216,  75.30425294,  83.55746401,
        88.85790966, 119.53829003, 101.19338231,  98.98206873,
       109.82049429, 111.88309524,  89.89277082, 122.93137713,
        98.52300216,  85.73070237,  75.81718021, 117.33582672,
       101.24451055,  93.36865888,  88.95055984,  82.26505838,
        91.5642877 ,  87.08698635, 112.2814647 , 110.84055334,
        88.45599107, 104.68747758, 110.30015876,  95.01518643,
        87.5728736 ,  80.10610268, 125.77541659, 101.65566989,
       106.5366883 , 115.78035678, 122.86289253,  83.56878218,
       108.79985024,  91.43993505, 117.53037807, 119.36267637,
        96.36082878, 100.03321025,  98.50251197, 100.83666409,
       100.00836486,  97.1746535 ,  80.2018804 ,  96.91846521,
       100.47058736, 102.8387626 ,  85.65686409, 124.73213443,
       103.30598437, 103.65438295, 100.44261189, 128.17859695,
        90.64113549, 105.86871348,  68.14808475, 109.1333392 ,
       102.16674439,  74.91421699, 114.06143402, 100.25079481,
       115.81030074, 118.69334278,  47.90014838,  88.41766105,
        52.39967411,  99.81704079,  97.48035681,  96.87765546,
       116.32759079,  76.81302019, 126.43028952, 119.02593127,
       128.95450411,  91.67375938,  95.07901449, 106.6418825 ,
        79.88431091,  74.6949942 ,  89.82261894, 107.12757045,
       114.12508159,  72.3378624 , 116.11324716, 102.7165555 ,
        82.25840378,  77.13856663,  86.83295187, 104.69719685,
        66.01098525, 103.99518813,  88.07081222, 127.39907336,
       129.44403613,  97.20161835,  94.78183787, 130.50462192,
        96.50792021,  89.85995846,  86.67029496, 102.57599252,
        83.86220501, 116.38524141,  67.79272454,  90.64631165,
       118.24778725,  80.66332009, 106.53119021,  75.55085492,
        98.49203076, 112.84554929,  89.07381508, 105.33323092,
        87.22558389, 126.68319375,  89.6938868 , 116.10604186,
        71.48001235,  95.31543597,  87.09149655,  75.83226466,
       119.44444024,  79.83150388, 104.64609544, 101.2993298 ,
       110.56444721, 105.90836867, 100.86298261,  95.70068602,
       106.85127149, 103.31753701, 107.29899441, 106.95378648,
        84.53124706,  91.30593827,  92.44742818,  96.74516798,
       121.16452901, 107.11459643,  96.4822386 , 103.8168835 ,
       119.2226488 ,  73.40866159,  99.44297209, 113.64381334,
        97.39001131, 124.1822525 , 116.37797461,  97.7385117 ,
       107.69403454,  96.98189065, 120.33663776, 119.1680594 ,
       111.96392069,  99.81665768, 102.92249446, 121.13983956,
       111.48978207,  85.92747972, 140.10879422, 108.53449617,
        91.88850085,  82.23535224, 106.92698635,  95.77181052,
       100.57140914,  74.34200881,  90.87766514,  89.71130589,
        96.37936535,  92.24928716, 101.81485397, 109.30688259,
       104.4015353 ,  84.60861529,  97.76388452, 126.5118527 ,
        82.49894719, 113.01468101, 101.65992096,  84.09047172,
        96.14894619,  89.06642421,  91.55377338, 102.40645164,
        88.5691672 ,  97.14489695,  95.23873535,  83.49164371,
        78.46419003, 108.68405623, 103.54206892,  85.79250819,
       107.67495748,  96.86932536,  82.95084213, 133.02521716,
        89.44203486, 130.83464453,  93.90225147, 116.37419437,
        82.0849017 ,  75.78186169, 123.96072686, 113.37978769,
        98.5860613 , 110.71053147,  91.7712663 , 107.34842159,
       104.79723419, 102.15450636,  85.17267378, 106.82313322,
       134.00451392, 104.98755303,  90.51756825,  88.88280813,
       127.99279123, 121.29768055, 110.47382454, 112.77866616,
       115.66112835,  96.54893485,  90.45129745,  87.91660401,
       108.36576849,  94.53650499,  81.08268347, 103.83916856,
       127.13794611,  93.63478127, 100.44015754, 107.91753398,
       116.46911799, 141.72593308, 110.78072008, 122.03373806,
       101.2503778 , 122.0283002 , 111.26015033,  92.51648347,
       107.7238954 , 126.9466481 , 117.51074034,  91.92542103,
       112.33834231,  95.48997335,  63.69329998, 111.2132889 ,
        98.61024931,  72.27077515, 115.38206075,  99.17868499,
        99.09822516,  96.84498411, 117.39436426,  95.95315251,
       111.11308082,  81.01777252, 104.94640209, 117.44990753,
        82.32743947, 119.09607258, 108.83590907,  78.58092846,
        62.0871696 ,  93.38897766,  77.15858758,  90.76380775,
       102.78351284, 119.31548817, 103.32715877,  95.84365903,
        89.71644414, 140.7735474 ,  94.86787842, 113.36670368,
        92.83545997, 112.81938015,  97.87471641,  98.58691837,
       119.10155464,  92.03914526, 101.89956239,  77.73330788,
        95.26731966, 120.53468671,  76.93631784, 101.98697558,
       112.04729901, 104.53505013, 125.45492051,  94.25641911,
       108.00537303, 100.73708039, 116.8667402 ,  74.8034582 ,
       105.42645314,  97.59685956,  93.69598779,  84.82541583,
       103.6946451 , 119.06818719,  81.40487205, 136.58354029,
        93.69525679,  76.68930454, 123.22560704,  96.00130871,
        98.39593363, 104.1271475 , 105.63521202,  95.46698614,
       106.5590369 , 115.77394541,  91.38346543,  85.17124024,
        98.05460848, 100.54326622,  95.37912471,  94.27097782,
        98.88143095,  81.61212371,  92.81914898, 114.84888379,
       120.51514555,  70.46438757,  92.24029977, 100.45109001,
        88.47235485, 111.58992807,  87.9912086 , 128.40310299,
        73.91558285, 132.89067797, 116.72742163, 104.52014638,
       103.12079788, 118.97974417, 104.2423292 , 114.66991961,
       120.02403253,  99.60956887, 108.94366375,  94.1151957 ,
       117.19266278,  97.32133922, 114.42200884, 102.82930476,
        82.36007522, 111.56699027,  86.39498039, 136.90890185,
       127.12843535, 124.03895462,  92.36814179, 113.57340611,
        99.46613766,  86.592966  , 128.32181382,  71.73011049,
       105.38906029,  99.39241858, 102.53247614,  94.84673522,
        97.18433817,  90.75661634,  76.03947385,  91.79346224,
       136.33614909, 112.9593768 , 117.47195616, 101.5297187 ,
       117.2773518 , 100.8225796 , 113.32797524,  94.86367287,
       102.01399212,  97.51978004,  97.19689959, 100.35353046,
       126.03167317, 110.6300365 , 111.99383527,  86.97309565,
        82.2712167 , 102.81477081,  87.71438605, 121.46703707,
       106.00415719, 103.82489634, 121.94370004, 110.04508524,
       107.41605563, 104.84468466,  90.06382006, 101.95583762,
       108.1411906 , 105.22763346,  99.38668431,  79.86602092,
        99.19682123,  86.69774176, 112.39385711,  95.92517569,
       112.197612  ,  76.08272695, 110.93866355, 109.79528555,
       102.23622676,  88.80347346,  82.48130571, 123.20529306,
        86.09221191, 131.19885023, 134.93181426,  81.87462664,
       118.93554086,  88.45958519,  99.05521067,  96.01100533,
        82.99436294,  96.2385793 , 125.96035549,  88.8406186 ,
        89.17094066,  94.53227274,  80.43328745,  86.88736823,
       106.95654558,  86.18704387, 123.97951784, 103.93147699,
        92.4349608 ,  91.1831139 ,  95.27148374, 128.96644764,
        96.1499696 , 107.12500201,  90.63727663, 119.7663574 ,
       140.9926504 , 123.35630383,  81.34438846, 109.39153921,
        89.95759359,  95.23218705,  87.23532059,  87.05103451,
       100.12516995, 128.46215095,  83.8977715 ,  77.61202923,
        81.96950461, 102.16308713,  88.23147873,  89.18985451,
       129.92731681, 103.07592095,  75.93943152, 123.45334813,
       125.79782535, 126.00301966,  89.12358122, 115.12796938,
        89.00947743, 128.16463921, 116.05946601,  95.38076666,
        78.67903841,  89.43456683, 109.14713932,  80.07736439,
        96.14295224,  74.21032368, 101.25279221,  86.13402353,
        81.51598066, 101.62306068,  86.09196614, 102.58021087,
        97.40436239,  64.91220183,  96.83556529, 112.84318409,
       127.04503377, 119.2749416 , 105.43320901, 106.96830534,
        90.83272419, 125.58811285,  74.75920861, 106.81045379,
       111.49654255, 116.01154566, 101.94932907, 117.73509818,
       103.39119034,  85.32462419, 105.41043669, 129.75866713,
       125.21194575,  84.63109642,  86.81723862, 122.99801165,
        96.96167702,  99.03822114,  84.5474574 ,  80.30498553,
        76.2120267 ,  81.4965143 , 112.10930477,  91.6826363 ,
       104.37060586,  77.93077284,  98.10613522, 102.40564455,
        90.00551752, 125.31794298,  96.45346951, 110.32950301,
        98.75259591, 102.82507726, 112.36158681, 107.10824121,
       111.14877152,  99.3601191 ,  84.3976524 , 110.40505404,
       119.94006173,  95.50036338,  97.92560493, 107.49121801,
       110.84798125,  92.89522133, 107.06594367, 104.46702805,
        98.33666058, 108.33751157,  76.0466159 , 101.5968674 ,
       105.19793313,  82.35260198, 126.17030459, 105.14850045,
       101.61769155,  83.90252538,  76.68699169, 111.57804493,
       105.69917453,  84.27961541, 106.47505261,  90.75945538,
        85.58867105,  91.14113656,  89.20329133, 119.53092737,
        76.7523127 ,  87.909865  ,  79.93305706,  99.73659612,
       117.11988891, 108.49507718, 105.25147981,  97.25671606,
        83.23706082,  94.14569998,  91.30272957, 124.54726515,
       124.06795453, 104.57516279,  89.63275977, 109.68264835,
       106.33664723, 123.71464671, 100.46073217,  96.7492384 ,
       135.62691266,  97.54465416, 112.53709388, 116.20412523,
       108.20031024,  90.62413421, 107.44717059, 101.94967334,
       104.68387553, 110.73751706,  96.88928347,  92.25779951,
       112.84611312,  77.174913  ,  95.94932489,  75.76082065,
        98.76854583,  97.47823253, 112.04655051, 106.19218877,
       123.99467979,  93.08521825,  93.6683191 ,  86.53573132,
        98.14662003, 103.00967939,  95.06228855,  95.65500282,
       107.38300452,  77.31682414,  99.05528567, 106.16309426,
       126.40893882, 109.44088751, 116.07298288,  99.61893866,
       102.95673053, 124.57507341, 107.90607533,  96.2325507 ,
        86.00377934, 112.4136391 ,  94.2407459 ,  97.21794675,
       118.30265305, 102.28770616, 107.47875546,  93.26346643,
       108.68216245,  77.17581455,  88.95689932,  87.75419757,
        90.8193631 ,  87.11259709,  91.56491396,  85.64275943,
       105.17691725, 116.98740433,  87.65282627,  93.02597743,
       118.55015162, 115.58683085,  64.85645091,  98.37512258,
        98.26577871, 110.10101637, 101.89441412,  75.25841149,
       110.70616557,  87.71485392,  90.90697728, 105.59976478,
        82.95173995, 119.50950921,  66.02493996, 103.96456125,
        66.09486846, 104.77517189, 110.04179525,  86.21080976,
        94.16714703, 105.90599967,  96.76815693,  96.62956579,
        89.6221521 ,  79.04695572,  86.40084445,  83.55031932,
       114.56831955, 121.5448307 , 101.07418797, 125.14476877,
        87.10039909, 106.06189221, 110.79744805, 101.85677356,
        93.0288334 ,  85.29216135, 102.87797408, 106.13440081,
       100.78212828, 120.99719353, 121.6932387 , 110.39553864,
        87.05469235, 111.82209947, 143.84256069,  94.92262269,
       105.06011706,  76.0110831 , 117.6545042 ,  93.07208343,
        91.35792424,  92.12038639,  78.96787163, 111.15115791,
        84.57792867, 111.9661951 ,  98.02472266, 105.20431725,
       134.91042174,  83.77799502,  96.87793252, 108.48605414,
       101.18168405,  97.39167633, 106.2440679 , 122.50389708,
       107.58864977,  94.6554237 , 113.39294504,  79.19893872,
       104.83878046, 109.38740722, 103.77369315, 127.33453243,
        80.49232629,  94.61986498,  99.32817585, 124.50360916,
       131.87967667,  91.74436937, 102.32579513,  91.91080844,
        83.18783587,  79.15829653, 120.6807937 , 129.95406294,
       120.12093521, 106.10784055,  91.30156548, 132.56996473,
        99.01596931, 102.22952193, 102.52306212, 113.16079569,
        88.14672175,  82.56584656, 115.81726148,  77.66385247,
        95.4394779 , 101.51050582,  88.74802152,  77.97120731,
        84.98085155, 143.43165322,  84.9266155 , 108.73773581,
       106.89115446, 120.49443791, 105.70087171,  76.9623472 ,
       104.74980874,  96.80766889, 124.62680474,  91.46199836,
        87.957923  , 126.11913965,  89.12985058, 121.73517831,
       104.87517958, 110.03301273,  81.60040992, 111.54047789,
        98.34482158, 102.08142665, 101.50397698, 116.18449135,
       100.03890205,  97.5479196 , 107.32979782, 117.03234832,
        82.50557745, 102.42787886,  70.36616985,  82.78498553,
        98.98634454,  92.49896857, 101.88833751, 103.01782585,
        70.12851305, 124.04805926, 137.52115507,  85.55390416,
       124.84950907,  91.58806899, 104.31699065,  87.33026885,
        99.0267132 ,  86.64867913, 110.41774124,  98.19735786,
        76.04523935, 124.14046152, 101.42666844,  98.52840101,
       113.88987728,  56.28476241,  94.45389159, 112.10687578,
       103.18320718,  98.43932172,  95.76814203,  95.96188838,
       123.53746742, 111.82904235,  64.52220302, 105.61434466,
        84.45751293, 109.93736059, 108.96754501,  79.80836972,
        64.13160649,  83.18565229, 105.62323377,  98.21135869])

Compute the **mean**, **median**, and **mode**

In [10]:
mean = np.mean(samples)
median = np.median(samples)
mode =  %timeit stats.stats.mode(samples)

AttributeError: module 'scipy' has no attribute 'stats'

In [ ]:
mean

99.88733450698744

In [ ]:
median

100.02360970849514

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [ ]:
min = np.min(samples)
max = np.max(samples)
q1 = np.percentile(samples, 25, interpolation = 'midpoint')
# numpy.percentile(a, q, axis=None, out=None, overwrite_input=False, 
# method='linear', keepdims=False, *, interpolation=None)
q3 = np.percentile(samples, 75, interpolation = 'midpoint')
iqr = q3- q1

In [ ]:
min

49.467386226802944

In [ ]:
max

145.1987155607604

In [ ]:
q1

89.67267405161475

In [ ]:
q3

109.58231505911704

In [ ]:
iqr

19.909641007502287

Compute the **variance** and **standard deviation**

In [ ]:
variance = np.var(samples)
std_dev = np.std(samples)

In [ ]:
variance

232.72233932136308

In [ ]:
std_dev

15.255239733329761

Compute the **skewness** and **kurtosis**

In [ ]:
skewness = stats.stats.skew(samples)
skewness

-0.007196495052755583

In [ ]:
kurtosis = stats.stats.kurtosis(samples)
kurtosis

-0.014375826111582946

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [ ]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [ ]:
y = np.array([5,3,7,6,10,14,19,35,94,58])
y

array([ 5,  3,  7,  6, 10, 14, 19, 35, 94, 58])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [ ]:
r = np.corrcoef(x,y)
r

array([[1.        , 0.80323888],
       [0.80323888, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

In [ ]:
x

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [ ]:
y

0     2
1     1
2     4
3     5
4     8
5    12
6    18
7    25
8    96
9    48
dtype: int64

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r = x.corr(y)  
r

0.7586402890911867

In [ ]:
r = y.corr(x)  
r

0.7586402890911869

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho = x.corr(y, method='spearman')
rho

0.9757575757575757

## Seaborn Dataset Tips

Import Seaborn Library

In [ ]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [ ]:
tips = sns.load_dataset("tips")
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [ ]:
tips.describe(include='all')

        total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [ ]:
tips.corr()

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000